Use `pull_request_target` instead of `pull_request` event (#2222)
This fixes issue:

```
HttpError: Resource not accessible by integration
            at /home/runner/work/_actions/infection/tests-checker-action/v1.0.2/webpack:/typescript-action/node_modules/@octokit/request/dist-node/index.js:86:1
```

solution from: https://github.com/orgs/community/discussions/57878#discussioncomment-6168449

> The problem is that your workflow is running for a pull_request event. For PRs from forks the GITHUB_TOKEN gets read-only permissions (so people can't make PRs to do malicious stuff in the target repository).