Allow installing the latest symfony packages during tests (#3244)
This should find issues like
https://github.com/infection/infection/issues/3243 reproduced for
Syfmony 8.1 `symfony/console` package.

- [ ] ~Now the build should pass as sanmai already provided a fix:
https://github.com/sanmai/di-container/releases/tag/0.1.13~
  - Actually this build confirms it's still fails
  - 0.1.14 doesn't fix this as well
- [ ] waiting for the fix to make the build green (should fix  #3243)


Failed build:
https://github.com/infection/infection/actions/runs/26676882874/job/78630265564?pr=3244#step:14:20

```

1) Infection\Tests\Container\ContainerTest::test_it_can_provide_all_services with data set "getAdapterInstallationDecider" ('Infection\TestFramework\Adapt...ecider', 'getAdapterInstallationDecider', Infection\Container\Container Object (), Infection\Tests\Reflection\ContainerReflection Object (...))
ReflectionException: Class "Symfony\Contracts\EventDispatcher\EventDispatcherInterface" does not exist

/home/runner/work/infection/infection/vendor/sanmai/di-container/src/Container.php:260
/home/runner/work/infection/infection/vendor/sanmai/pipeline/src/Standard.php:430
/home/runner/work/infection/infection/vendor/sanmai/pipeline/src/Standard.php:750
/home/runner/work/infection/infection/vendor/sanmai/di-container/src/Container.php:221
/home/runner/work/infection/infection/vendor/sanmai/di-container/src/Container.php:191
/home/runner/work/infection/infection/vendor/sanmai/di-container/src/Container.php:261
/home/runner/work/infection/infection/vendor/sanmai/pipeline/src/Standard.php:430
/home/runner/work/infection/infection/vendor/sanmai/pipeline/src/Standard.php:750
/home/runner/work/infection/infection/vendor/sanmai/di-container/src/Container.php:221
/home/runner/work/infection/infection/vendor/sanmai/di-container/src/Container.php:191
/home/runner/work/infection/infection/src/Container/Container.php:1006
/home/runner/work/infection/infection/tests/phpunit/Container/ContainerTest.php:202
```

---------

Co-authored-by: Alexey Kopytko <alexey@kopytko.com>