When IgnoreMutator decorator class is used, work with underlying class of mutator to get its definition (#1972)
* When IgnoreMutator decorator class is used, work with underlying class of mutator to get its definition

Fixes:

```
DomainException: The class "Infection\Mutator\IgnoreMutator" does not have a definition
```

on StrykerHtmlReportBuilder.php

Bug has been introduced in https://github.com/infection/infection/pull/1686/files#diff-01143bfb1cd8c30fa7f368e58fa5b9bebf3f35de2a4bc509123ed81358b59ff8R249

* Fix phpstan type error