PHPUnit-Bridge 4.3.3 and earlier are broken with PHPUnit 8.2.5+. (#766)
* Keep from upgrading to PHPUnit 8.3

* PHPUnit-Bridge 4.3.3 and earlier are broken with PHPUnit 8.2.5+

Getting:

> Error: Call to undefined method PHPUnit\Util\ErrorHandler::handleError()

* Isolate E2E tests

PHPUnit 8+ started to change APIs rapidly, therefore versions of the same branch may be interface-incompatible.

* Skip E2E tests if coverage cannot be collected under PHPDBG